spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/bootdb2
    username: bootdb2user
    password: bootdb2user
    hikari:
      minimum-idle: 2
      maximum-pool-size : 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org:
      springframework:
        security:
          web: TRACE